# Generated by Django 5.1.5 on 2025-01-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='age',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='type',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='animals',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='animals',
            name='image',
            field=models.ImageField(default='./media/pet_photos/cat-1.jpg', upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
