# Generated by Django 5.1.5 on 2025-01-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animals_age_remove_animals_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=20, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.JSONField()),
                ('features', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
