# Generated by Django 5.1.5 on 2025-04-18 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_editedpetimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editedpetimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Edited Pet Image', 'verbose_name_plural': 'Edited Pet Images'},
        ),
        migrations.AlterField(
            model_name='editedpetimage',
            name='edit_metadata',
            field=models.JSONField(default=dict, help_text='JSON store of editing parameters and history'),
        ),
        migrations.AlterField(
            model_name='editedpetimage',
            name='edited_image',
            field=models.ImageField(blank=True, help_text='Edited version of the image', null=True, upload_to='edited_pet_images/'),
        ),
        migrations.AlterField(
            model_name='editedpetimage',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Original uploaded image file', null=True, upload_to='original_pet_images/'),
        ),
        migrations.AlterField(
            model_name='editedpetimage',
            name='pet',
            field=models.ForeignKey(help_text='The pet this edited image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='edited_images', to='accounts.pet'),
        ),
        migrations.AddIndex(
            model_name='editedpetimage',
            index=models.Index(fields=['created_at'], name='accounts_ed_created_1ae11a_idx'),
        ),
    ]
