# Generated by Django 5.1.5 on 2025-04-18 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_editedpetimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='editedpetimage',
            name='accounts_ed_pet_id_c82e1a_idx',
        ),
        migrations.RemoveField(
            model_name='editedpetimage',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='editedpetimage',
            name='pet',
        ),
        migrations.AlterField(
            model_name='editedpetimage',
            name='edited_image',
            field=models.ImageField(default=' ', help_text='The edited image file', upload_to='edited_pet_images/'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='editedpetimage',
            index=models.Index(fields=['owner'], name='accounts_ed_owner_i_421b5e_idx'),
        ),
    ]
